### ISSUE TITLE
switch color theme is broken 

### ISSUE THREAD

**Issue by putchar** [aaranxu/adidoks#41]
Hello and thank you for making this theme

it seems the commit `afd55736a9ba7b8ed01e111b4ebf4a44dcc8e998` broke something in the theme switcher

![image](https://user-images.githubusercontent.com/8208767/149537106-d874eb48-5b49-47f3-a0e2-d0ebb87e71bd.png)
when i click on it it stays white , it should switch to the black theme

i have no real skills in html / css and i really do not know where to look at

Regards

**Comment by putchar** [comment]
i think the answer is here: https://github.com/aaranxu/adidoks/pull/40

**Comment by ajyoon** [comment]
I can't reproduce this issue, what browser are you on? Does the devtools console show any errors when you click the button?

**Comment by putchar** [comment]
hello @ajyoon .
as i previously said the culprit was the commit i mentioned above
everything seems to be working now and i will close this issue.
